version: '3'

services:
    app:
        image: golang:1.14
        container_name: digitalocean_volumes_backup.app
        hostname: digitalocean_volumes_backup.app
        working_dir: /app
        stdin_open: true
        tty: true
        environment: 
            ACCESS_TOKEN: 8c97cbda79c6671fa2164b1650529c44c3227c215fb6b2b8321f51db7917c77e
            VOLUMES_BACKUP: 
            SNAPSHOTS_PREFIX: backup
            SNAPSHOTS_MAX: 5
        volumes:
            - ./:/app
